version: "3.9"

services:
  api:
    build:
      context: ../DockerLab02-DockerizingDotNetAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=AiDb;User Id=sa;Password=YourStrong@Passw0rd
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
