namespace JWTAuthService.Models;

// ============================================================
//  USER ENTITY
//  -----------
//  This is the database entity mapped to the [Users] table.
//  It is NOT exposed directly to the API — DTOs are used instead.
//
//  SECURITY NOTE:
//  PasswordHash stores a bcrypt/PBKDF2 hash, NEVER plain text.
//  The hash is generated by PasswordHasher<User> from ASP.NET Core Identity.
// ============================================================

/// <summary>
/// Represents an application user stored in the database.
/// </summary>
public class User
{
    /// <summary>Primary key — auto-generated identity.</summary>
    public int Id { get; set; }

    /// <summary>User's full display name.</summary>
    public string FullName { get; set; } = string.Empty;

    /// <summary>Unique email address used for login.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Hashed password — never store plain text.
    /// Generated by ASP.NET Core Identity's PasswordHasher.
    /// </summary>
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>
    /// User role — controls access to protected endpoints.
    /// Values: "Admin" | "User"
    /// </summary>
    public string Role { get; set; } = "User";

    /// <summary>UTC timestamp when the account was created.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
