using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EFCoreLab03.Migrations;

/// <summary>
/// InitialCreate migration — generated by:
///   dotnet ef migrations add InitialCreate
///
/// This file was scaffolded automatically by EF Core Tools.
/// It contains the Up() method (apply changes) and
/// Down() method (revert changes).
///
/// Apply with: dotnet ef database update
/// Revert with: dotnet ef database update 0
/// </summary>
public partial class InitialCreate : Migration
{
    /// <summary>
    /// Up() — creates the database schema.
    /// Called when you run: dotnet ef database update
    /// </summary>
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Create Categories table first (no foreign keys)
        migrationBuilder.CreateTable(
            name: "Categories",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Categories", x => x.Id);
            });

        // Create Suppliers table (no foreign keys)
        migrationBuilder.CreateTable(
            name: "Suppliers",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Name = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                Email = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                Phone = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Suppliers", x => x.Id);
            });

        // Create Products table (depends on Categories and Suppliers)
        migrationBuilder.CreateTable(
            name: "Products",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                Price = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                StockQuantity = table.Column<int>(type: "int", nullable: false),
                CategoryId = table.Column<int>(type: "int", nullable: false),
                SupplierId = table.Column<int>(type: "int", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Products", x => x.Id);
                table.ForeignKey(
                    name: "FK_Products_Categories_CategoryId",
                    column: x => x.CategoryId,
                    principalTable: "Categories",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "FK_Products_Suppliers_SupplierId",
                    column: x => x.SupplierId,
                    principalTable: "Suppliers",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        // Create unique index on Categories.Name
        migrationBuilder.CreateIndex(
            name: "IX_Categories_Name",
            table: "Categories",
            column: "Name",
            unique: true);

        // Create index on Products.CategoryId for faster joins
        migrationBuilder.CreateIndex(
            name: "IX_Products_CategoryId",
            table: "Products",
            column: "CategoryId");

        // Create index on Products.SupplierId for faster joins
        migrationBuilder.CreateIndex(
            name: "IX_Products_SupplierId",
            table: "Products",
            column: "SupplierId");
    }

    /// <summary>
    /// Down() — reverts the migration (drops all tables).
    /// Called when you run: dotnet ef database update 0
    /// </summary>
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Drop in reverse order to respect foreign key constraints
        migrationBuilder.DropTable(name: "Products");
        migrationBuilder.DropTable(name: "Categories");
        migrationBuilder.DropTable(name: "Suppliers");
    }
}
